### 注册用户
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "student_id": "20213001",
  "password": "123456",
  "nickname": "测试用户",
  "school_name": "某某大学"
}

### 登录
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "student_id": "20213001",
  "password": "123456"
}